[metadata]
creation_date = "2021/09/27"
maturity = "production"
updated_date = "2021/09/27"
min_stack_version = "7.12.0"

[rule]
author = ["Elastic"]
description = """
Identifies a suspicious process access event by LSASS where the granted access value is equal to duplicate process handle
and from an unknown call trace module. This may indicate an attempt to dump Lsass memory using MirrorDump tool in preparation
for credential access.
"""
from = "now-9m"
index = ["winlogbeat-*", "logs-windows.*"]
language = "kuery"
license = "Elastic License v2"
name = "Potential Credential Access via MirrorDump"
references = ["https://github.com/CCob/MirrorDump"]
risk_score = 47
rule_id = "02a4576a-7480-4284-9327-548a806b5e48"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Credential Access"]
timestamp_override = "event.ingested"
type = "query"

query = '''
event.category:process and event.code:"10" and process.name :"lsass.exe" and winlog.event_data.GrantedAccess :"0x40" and
winlog.event_data.CallTrace :*UNKNOWN*
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1003"
name = "OS Credential Dumping"
reference = "https://attack.mitre.org/techniques/T1003/"

  [[rule.threat.technique.subtechnique]]
  name = "LSASS Memory"
  id = "T1003.001"
  reference = "https://attack.mitre.org/techniques/T1003/001/"

[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"
