[metadata]
creation_date = "2020/10/13"
maturity = "developement"
updated_date = "2020/10/13"

[rule]
author = ["Elastic"]
description = """
Identifies unusual child processes of svchost services that normally spawn limited child processes. This may indicate a
code injection or an equivalent form of exploitation.
"""
false_positives = ["Changes to Windows Services or an rarely executed child process."]
from = "now-9m"
index = ["logs-endpoint.events.*", "winlogbeat-*"]
language = "eql"
license = "Elastic License"
name = "Unusual Svchost Child Process"
risk_score = 47
rule_id = "780ef94a-dc82-4f80-a604-a50ee2e79e6f"
severity = "medium"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Defense Evasion", "Privilege Escalation"]
type = "eql"

query = '''
process where event.type == "start" and process.parent.name=="svchost.exe" and
 /* Svchost services based on -s arg that spawn a limited number of known child processes */ 
 process.parent.args:("Appinfo","dmwappushservice","PcaSvc","TabletInputService","UsoSvc","WerSvcGroup","lfsvc","wuauserv","utcsvc",
                      "DPS","DeviceAssociationService","TokenBroker","wscsvc","ClipSVC","WinHttpAutoProxySvc","LanmanServer","LocalServiceNetworkFirewall",
                      "UserManager","SessionEnv","SENS","NcbService","PlugPlay","Winmgmt","Themes","SysMain","AudioEndpointBuilder","AppXSvc","RPCSS","WaaSMedicSvc",
                      "GPSvcGroup","termsvcs","TermService","NcaSvc","LSM","SDRSVC") and
   /* FPs can be added below */
 not process.name : ("WerFault.exe","WerFaultSecure.exe","rundll32.exe","consent.exe","ctfmon.exe","deviceenroller.exe","omadmclient.exe","UsoClient.exe",
                     "MusNotificationUx.exe","wermgr.exe","Headlesshost.exe","sc.exe","wuauclt.exe","dasHost.exe","UtcDecoderHost.exe","dtdump.exe","TTTracer.exe",
                     "dsregcmd.exe","RdrLeakDiag.exe","TokenBrokerCookies.exe","MsMpeng.exe","upgrade.exe","ClipUp.exe","DeviceCensus.exe","pacjsworker.exe",
                     "audiodg.exe","wlanext.exe","hotspothost.exe","dism.exe","sihost.exe","mobsync.exe","RDVGHelper.exe","RdpSaUacHelper.exe","ntsd.exe",
                     "CheckPointVpnPluginApp.exe","wmidap.exe","w3wp.exe","wwahost.exe","ByteCodeGenerator.exe","WaaSMedicAgent.exe","gpscript.exe",
                     "dllhost.exe","rdpclip.exe","mcrmgr.exe","sdclt.exe","WMIADAP.exe","MpCmdRun.exe","MusNotifyIcon.exe","CompatTelRunner.exe","Defrag.exe",
                     "TabTip.exe","omadmprc.exe","DismHost.exe","WindowsUpdateBox.exe","SrTasks.exe","OfficeC2RClient.exe","winlogon.exe","csrss.exe","wininit.exe")
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1093"
name = "Process Hollowing"
reference = "https://attack.mitre.org/techniques/T1093/"


[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1055"
name = "Process Injection"
reference = "https://attack.mitre.org/techniques/T1055/"


[rule.threat.tactic]
id = "TA0005"
name = "Defense Evasion"
reference = "https://attack.mitre.org/tactics/TA0005/"

